
package com.shuwen.client.clientService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserWebService", targetNamespace = "http://webService.com/web")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserWebService {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.webservice.web.ResponseWrapper
     */
    @WebMethod
    @WebResult(name = "ResponseWrapper", targetNamespace = "http://webService.com/web", partName = "parameters")
    public ResponseWrapper save(
        @WebParam(name = "RequestWrapper", targetNamespace = "http://webService.com/web", partName = "parameters")
        RequestWrapper parameters);

}
